import { mergeDemoPrice } from '@/data/priceBook';
import type { DemoState } from './model';

export const createDemoState = (): DemoState => {
  const state: DemoState = {
    schemaVersion: 1,
    hydrated: false,
    dataMode: 'sandbox',
    authStatus: 'disabled',
    setupComplete: false,
    role: 'owner',
    online: true,
    syncRevision: 18,
    selectedLeadId: 'lead-morgan',
    selectedVisitId: 'visit-morgan',
    leads: [
      {
        id: 'lead-morgan',
        name: 'Morgan Ellis',
        initials: 'ME',
        source: 'Web',
        service: 'Driveway + gutter cleaning',
        address: '1842 Cedar Ridge Lane',
        city: 'Flower Mound, TX 75028',
        stage: 'new',
        value: '$0',
        age: '12 min',
        phone: '(214) 555-0184',
        email: 'morgan.ellis@example.com',
        priority: 'high',
        consent: true,
        note: 'Two-story home. Customer uploaded three photos and prefers Friday morning.',
      },
      {
        id: 'lead-avery',
        name: 'Avery Chen',
        initials: 'AC',
        source: 'SMS',
        service: 'House soft wash',
        address: '906 Larkspur Court',
        city: 'Grapevine, TX 76051',
        stage: 'new',
        value: '$0',
        age: '28 min',
        phone: '(817) 555-0130',
        email: 'avery.chen@example.com',
        priority: 'normal',
        consent: true,
        note: 'Asked whether weekend appointments are available.',
      },
      {
        id: 'lead-jordan',
        name: 'Jordan Patel',
        initials: 'JP',
        source: 'Phone',
        service: 'Gutter + downspout cleaning',
        address: '3821 Moss Haven Drive',
        city: 'Dallas, TX 75231',
        stage: 'estimated',
        value: '$389',
        age: '2 hr',
        phone: '(469) 555-0166',
        email: 'jordan.patel@example.com',
        priority: 'normal',
        consent: true,
        note: 'Estimate is within policy and ready to quote.',
      },
      {
        id: 'lead-sam',
        name: 'Sam Rivera',
        initials: 'SR',
        source: 'Email',
        service: 'Patio pressure wash',
        address: '7204 Meadow View',
        city: 'Plano, TX 75024',
        stage: 'quoted',
        value: '$472',
        age: '1 day',
        phone: '(972) 555-0108',
        email: 'sam.rivera@example.com',
        priority: 'normal',
        consent: true,
        note: 'Quote viewed twice; automated follow-up due at 3:00 PM.',
      },
      {
        id: 'lead-riley',
        name: 'Riley Brooks',
        initials: 'RB',
        source: 'Referral',
        service: 'Whole-property clean',
        address: '421 Oak Hollow Way',
        city: 'Southlake, TX 76092',
        stage: 'booked',
        value: '$1,184',
        age: '3 days',
        phone: '(817) 555-0172',
        email: 'riley.brooks@example.com',
        priority: 'normal',
        consent: true,
        note: 'Synthetic deposit, route, and weather fixtures are loaded for the sandbox scenario.',
      },
      {
        id: 'lead-drew',
        name: 'Drew Wallace',
        initials: 'DW',
        source: 'Chat',
        service: 'Driveway pressure wash',
        address: '1507 Parkstone Drive',
        city: 'Irving, TX 75063',
        stage: 'new',
        value: '$0',
        age: '3 hr',
        phone: '(214) 555-0155',
        email: 'drew.wallace@example.com',
        priority: 'normal',
        consent: true,
        note: 'Scope incomplete; AI asked for property address and driveway photos.',
      },
    ],
    estimate: {
      id: 'estimate-1048',
      leadId: 'lead-morgan',
      estimateNumber: 'EST-1048',
      status: 'draft',
      priceBookVersion: 'DFW Residential 2026.07 · v3',
      drivewaySqFt: '1250',
      gutterLinearFt: '188',
      downspoutCount: '4',
      stories: '2',
      surface: 'concrete',
      soil: 'moderate',
      access: 'clear',
      risk: 'standard',
      travelZone: 'DFW-A',
      discountPercent: '0',
      serviceSubtotal: '566.80',
      travelFee: '0.00',
      discount: '0.00',
      tax: '46.76',
      total: '613.56',
      deposit: '153.39',
      estimatedCost: '224.85',
      marginPercent: '60.3',
      durationMinutes: 214,
      formulaHash: 'sha256:a935b1f4…e98c',
      photoEvidence: {
        confidence: 0.87,
        observations: [
          'Concrete driveway with moderate organic staining',
          'Two-story roofline visible',
          'Gutter guards not visible',
        ],
        unknowns: ['Rear gutter access not shown'],
        humanVerified: true,
      },
    },
    approvals: [
      {
        id: 'approval-review',
        reason: 'negative_review_response',
        title: 'Negative review response',
        summary:
          'Finance agent drafted a response to a 2-star review. Policy requires owner approval before posting.',
        risk: 'high',
        status: 'pending',
        requestedAt: '9:14 AM',
        expiresAt: 'Jul 30, 5:00 PM',
        entityId: 'review-208',
        payloadPreview: 'Public reply on Google Business Profile · 92 words',
        policyVersion: 'communications-2026.07',
      },
      {
        id: 'approval-campaign',
        reason: 'campaign_send',
        title: 'August gutter reminder',
        summary: 'Send a consent-filtered seasonal reminder to 34 active customers.',
        risk: 'medium',
        status: 'pending',
        requestedAt: '8:42 AM',
        expiresAt: 'Jul 31, 12:00 PM',
        entityId: 'campaign-august',
        payloadPreview: '34 recipients · SMS · excludes 8 opted-out contacts',
        policyVersion: 'marketing-2026.07',
      },
    ],
    visits: [
      {
        id: 'visit-morgan',
        jobNumber: 'JOB-1048',
        customerName: 'Morgan Ellis',
        address: '1842 Cedar Ridge Lane, Flower Mound, TX 75028',
        service: 'Driveway + gutter cleaning',
        date: '2026-07-31',
        startsAt: '9:00 AM',
        endsAt: '12:45 PM',
        crew: 'Owner crew',
        status: 'ready',
        weather: {
          temperature: 79,
          precipitation: 18,
          windMph: 9,
          checkedAt: '8:01 AM',
          disposition: 'clear',
        },
        route: {
          driveMinutes: 31,
          miles: 20.4,
          checkedAt: '8:02 AM',
          feasible: true,
        },
        checklist: [
          {
            id: 'arrival',
            label: 'Arrival walkaround',
            detail: 'Confirm scope, access, drainage, and pre-existing damage',
            required: true,
            safetyCritical: true,
            complete: false,
          },
          {
            id: 'before',
            label: 'Before photos',
            detail: 'Minimum six property and condition photos',
            required: true,
            safetyCritical: false,
            complete: false,
          },
          {
            id: 'protect',
            label: 'Protect property',
            detail: 'Cover outlets, wet plants, confirm runoff plan',
            required: true,
            safetyCritical: true,
            complete: false,
          },
          {
            id: 'service',
            label: 'Complete approved service',
            detail: 'Work only within quote and current SOP',
            required: true,
            safetyCritical: true,
            complete: false,
          },
          {
            id: 'rinse',
            label: 'Final rinse and inspection',
            detail: 'Verify surfaces, drainage, and cleanup',
            required: true,
            safetyCritical: false,
            complete: false,
          },
          {
            id: 'after',
            label: 'After photos',
            detail: 'Match before angles and document exceptions',
            required: true,
            safetyCritical: false,
            complete: false,
          },
        ],
        beforePhotos: 0,
        afterPhotos: 0,
        signature: false,
        elapsedMinutes: 0,
        elapsedSeconds: 0,
        materials: [],
        notes: '',
      },
      {
        id: 'visit-riley',
        jobNumber: 'JOB-1032',
        customerName: 'Riley Brooks',
        address: '421 Oak Hollow Way, Southlake, TX 76092',
        service: 'House soft wash + driveway + gutters',
        date: '2026-07-28',
        startsAt: '10:30 AM',
        endsAt: '2:30 PM',
        crew: 'Owner crew',
        status: 'ready',
        weather: {
          temperature: 82,
          precipitation: 12,
          windMph: 7,
          checkedAt: '8:01 AM',
          disposition: 'clear',
        },
        route: {
          driveMinutes: 24,
          miles: 15.2,
          checkedAt: '8:02 AM',
          feasible: true,
        },
        checklist: [],
        beforePhotos: 0,
        afterPhotos: 0,
        signature: false,
        elapsedMinutes: 0,
        elapsedSeconds: 0,
        materials: [],
        notes: '',
      },
    ],
    incidents: [],
    invoices: [
      {
        id: 'invoice-1027',
        number: 'INV-1027',
        customerName: 'Taylor Nguyen',
        jobNumber: 'JOB-1027',
        issueDate: 'Jul 25, 2026',
        dueDate: 'Due today',
        total: '684.21',
        paid: '171.05',
        balance: '513.16',
        status: 'open',
      },
      {
        id: 'invoice-1021',
        number: 'INV-1021',
        customerName: 'Cameron Lee',
        jobNumber: 'JOB-1021',
        issueDate: 'Jul 18, 2026',
        dueDate: 'Jul 25, 2026',
        total: '438.70',
        paid: '0.00',
        balance: '438.70',
        status: 'past_due',
      },
      {
        id: 'invoice-1019',
        number: 'INV-1019',
        customerName: 'Jamie Ortiz',
        jobNumber: 'JOB-1019',
        issueDate: 'Jul 14, 2026',
        dueDate: 'Paid Jul 14',
        total: '927.42',
        paid: '927.42',
        balance: '0.00',
        status: 'paid',
      },
    ],
    remindedInvoiceIds: [],
    traces: [
      {
        id: 'trace-1',
        time: '9:22 AM',
        agent: 'Intake',
        action: 'Qualified Morgan Ellis',
        result: 'succeeded',
        detail: 'Used verified address, service intent, consent, and supplied photos.',
        traceId: 'tr_01J4YMX0',
        promptVersion: 'intake-v4.2',
      },
      {
        id: 'trace-2',
        time: '9:18 AM',
        agent: 'Scheduling',
        action: 'Checked Friday capacity',
        result: 'succeeded',
        detail: 'Owner crew has 315 minutes available; weather refresh required before dispatch.',
        traceId: 'tr_01J4YMV3',
        promptVersion: 'scheduling-v3.1',
      },
      {
        id: 'trace-3',
        time: '9:14 AM',
        agent: 'Follow-up',
        action: 'Drafted negative review reply',
        result: 'approval_required',
        detail: 'Public negative-review replies require exact-payload owner approval.',
        traceId: 'tr_01J4YMR7',
        promptVersion: 'followup-v5.0',
      },
      {
        id: 'trace-4',
        time: '8:42 AM',
        agent: 'Marketing',
        action: 'Prepared August reminder',
        result: 'approval_required',
        detail: 'Audience filtered by documented consent and opt-out state.',
        traceId: 'tr_01J4YJH2',
        promptVersion: 'marketing-v2.6',
      },
    ],
    auditEvents: [
      {
        id: 'audit-1',
        time: '9:22 AM',
        actor: 'agent:intake',
        action: 'lead.qualified',
        entity: 'lead-morgan',
        outcome: 'success',
        requestId: 'req_0f03a1',
        immutable: true,
      },
      {
        id: 'audit-2',
        time: '9:14 AM',
        actor: 'agent:follow_up',
        action: 'approval.requested',
        entity: 'approval-review',
        outcome: 'pending',
        requestId: 'req_0ef82c',
        immutable: true,
      },
      {
        id: 'audit-3',
        time: '8:02 AM',
        actor: 'sandbox:route_fixture',
        action: 'visit.route_fixture_recorded',
        entity: 'visit-morgan',
        outcome: 'synthetic',
        requestId: 'req_0e9912',
        immutable: true,
      },
    ],
    automations: [
      {
        id: 'auto-briefing',
        name: 'Owner morning briefing',
        trigger: 'Weekdays · 7:45 AM',
        status: 'succeeded',
        lastRun: 'Today, 7:45 AM',
        nextRun: 'Tomorrow, 7:45 AM',
        reversibility: 'reversible',
      },
      {
        id: 'auto-followup',
        name: 'Quote follow-up',
        trigger: '48 hours after viewed quote',
        status: 'scheduled',
        lastRun: 'Yesterday, 3:10 PM',
        nextRun: 'Today, 3:00 PM',
        reversibility: 'reversible',
      },
      {
        id: 'auto-review',
        name: 'Review and referral request',
        trigger: '2 hours after payment',
        status: 'scheduled',
        lastRun: 'Jul 26, 4:20 PM',
        nextRun: 'On next eligible payment',
        reversibility: 'reversible',
      },
      {
        id: 'auto-campaign',
        name: 'Seasonal maintenance reminder',
        trigger: 'Monthly audience refresh',
        status: 'waiting_approval',
        lastRun: 'Today, 8:42 AM',
        nextRun: 'After owner decision',
        reversibility: 'compensating_action',
      },
    ],
    notifications: [
      {
        id: 'notification-approval',
        title: '2 approvals need attention',
        body: 'Negative review reply and August reminder are waiting.',
        href: '/approvals',
        read: false,
      },
      {
        id: 'notification-invoice',
        title: 'Invoice INV-1021 is past due',
        body: '$438.70 outstanding for Cameron Lee.',
        href: '/finance',
        read: false,
      },
      {
        id: 'notification-weather',
        title: 'Friday weather check expires',
        body: 'Morgan Ellis visit needs a fresh NWS check before dispatch.',
        href: '/dispatch',
        read: false,
      },
    ],
    toasts: [],
    offlineQueue: [],
    integrations: [
      {
        id: 'openai',
        name: 'OpenAI',
        provider: 'Agents SDK',
        mode: 'Sandbox',
        status: 'Healthy',
        capabilities: ['structured agent runs', 'photo scope analysis', 'tracing'],
        lastCheck: '10 sec ago',
      },
      {
        id: 'twilio',
        name: 'Twilio',
        provider: 'Voice + SMS',
        mode: 'Sandbox',
        status: 'Healthy',
        capabilities: ['inbound SMS', 'outbound SMS', 'voice webhooks'],
        lastCheck: '12 sec ago',
      },
      {
        id: 'email',
        name: 'Email',
        provider: 'SMTP / Postmark adapter',
        mode: 'Sandbox',
        status: 'Healthy',
        capabilities: ['inbound parsing', 'transactional email', 'delivery events'],
        lastCheck: '12 sec ago',
      },
      {
        id: 'stripe',
        name: 'Stripe',
        provider: 'Checkout + Invoicing',
        mode: 'Sandbox',
        status: 'Healthy',
        capabilities: ['deposit checkout', 'invoice checkout', 'signed webhooks'],
        lastCheck: '14 sec ago',
      },
      {
        id: 'calendar',
        name: 'Google Calendar',
        provider: 'Calendar API',
        mode: 'Sandbox',
        status: 'Healthy',
        capabilities: ['visit sync', 'availability', 'duplicate protection'],
        lastCheck: '16 sec ago',
      },
      {
        id: 'maps',
        name: 'Maps & geocoding',
        provider: 'Provider adapter',
        mode: 'Sandbox',
        status: 'Healthy',
        capabilities: ['address normalization', 'coordinates', 'travel zones'],
        lastCheck: '18 sec ago',
      },
      {
        id: 'nws',
        name: 'NWS weather',
        provider: 'api.weather.gov',
        mode: 'Sandbox',
        status: 'Healthy',
        capabilities: ['forecast', 'alerts', 'operating policy checks'],
        lastCheck: '20 sec ago',
      },
      {
        id: 'vroom',
        name: 'VROOM',
        provider: 'v1.15.0 service',
        mode: 'Sandbox',
        status: 'Healthy',
        capabilities: ['route optimization', 'capacity constraints', 'time windows'],
        lastCheck: '21 sec ago',
      },
      {
        id: 'signed_storage_targets',
        name: 'Server-signed media targets',
        provider: 'Optional Supabase server adapter',
        mode: 'Sandbox',
        status: 'Healthy',
        capabilities: ['short-lived signed uploads', 'private signed downloads'],
        lastCheck: '22 sec ago',
      },
      {
        id: 'quickbooks',
        name: 'QuickBooks export',
        provider: 'CSV / IIF export',
        mode: 'Sandbox',
        status: 'Healthy',
        capabilities: ['invoice export', 'payment export', 'checksum manifest'],
        lastCheck: '24 sec ago',
      },
    ],
    customerPortalRequests: [],
    customerCommunicationPreferences: {
      transactionalSms: true,
      transactionalEmail: true,
      marketingSms: false,
      marketingEmail: false,
      globalOptOut: false,
      disclosureVersion: 'customer-portal-consent-v1',
      updatedAt: '2026-07-28T12:00:00.000Z',
      version: 1,
    },
    customerPortalServiceOptions: [
      { code: 'pressure-wash-flatwork', name: 'Driveway and flatwork pressure wash' },
      { code: 'soft-wash-house', name: 'House exterior soft wash' },
      { code: 'gutter-cleaning', name: 'Gutter and downspout cleaning' },
      { code: 'roof-washing', name: 'Roof soft wash' },
      { code: 'window-cleaning', name: 'Window cleaning' },
    ],
    customerQuoteAccepted: false,
    depositPaid: false,
    reviewRequested: false,
    referralInvited: false,
    recurringPlanActive: false,
  };

  return { ...state, estimate: mergeDemoPrice(state.estimate) };
};
